Add support for testing GW routers.
openvswitch/ovn-scale-test pull request #205
Opened 2020-08-06 08:45 UTC by dceara

2020-08-06 08:46 UTC, dceara commented
@hzhou8, when you have time it would be great if you could have a look at these changes, they upstream all the remaining code we were using in our downstream tests.

Thanks,
Dumitru

2020-08-24 05:05 UTC, hzhou8 requested changes

2020-08-24 05:05 UTC, hzhou8 commented on rally_ovs/plugins/ovs/ovnclients.py
> +        # Use the last IP (+ offset) in the CIDR as gateway IP.
This comment is confusing. Did you mean (- offset)?

2020-08-24 05:08 UTC, hzhou8 approved these changes

2020-08-24 05:48 UTC, hzhou8 commented
@dceara LGTM except a very minor comment.

2020-08-24 08:43 UTC, dceara commented on rally_ovs/plugins/ovs/ovnclients.py
> +        # Use the last IP (+ offset) in the CIDR as gateway IP.
Right, thanks for spotting it, i'll fix it.

2020-08-24 08:55 UTC, dceara commented
@hzhou8 thanks for the review, I'm merging the PR.

2020-08-24 08:55 UTC, merged